version: "3.1"
services:
  Testproject-agent:
    image: testproject/agent:latest
    container_name: testproject-agent
    depends_on:
      - chrome
      - firefox
    environment:
      TP_API_KEY: "M-OJQBbJmTVJrZa1VbKJ-Q4kHilkMs0RrhLOHQ0pR_A1"
      TP_JOB_ID: "xdRYnnvgHUWGfYvqcdftuA"
      TP_JOB_PARAMS: '"jobParameters" : { "browsers": [ "Chrome" ] }'
      CHROME: "chrome:4444"
      FIREFOX: "firefox:4444"
  chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
  firefox:
    image: selenium/standalone-firefox
    volumes:
      - /dev/shm:/dev/shm
